### ISSUE TITLE
Use CRD as the default persistence

### ISSUE THREAD

**Issue by Akrog** [embercsi/ember-csi-operator#13]
Instead of forcing every deployment to define CRD as the default persistence, we should be setting this as a default in the operator.

Since the operator is storing data in the "ember-csi" namespace, we know that it exists, so we can tell Ember-CSI to use it instead of the default one: `X_CSI_PERSISTENCE_CONFIG:       '{"storage":"crd","namespace":"ember-csi"}'`

**Comment by kirankt** [comment]
PR 22 has been redacted

**Comment by kirankt** [comment]
New PR created. Please review: https://github.com/embercsi/ember-csi-operator/pull/25
