### ISSUE TITLE
Support Ember-CSI container restarts and share locks

### ISSUE THREAD

**Issue by Akrog** [embercsi/ember-csi-operator#15]
As we currently deploy the Ember-CSI node containers, if we restart them we'll mess up things because they'll lose the private volume bind mounts.

If we have multiple Ember-CSI node containers running on the same host (we have multiple backends) we may run into problems since they are not sharing the locks.

To resolve these two issues we just need to mount the container's `/var/lib/ember-csi` directory into the host, and share this directory between all the Ember-CSI containers.

**Comment by kirankt** [comment]
This issue is addressed in PR: https://github.com/embercsi/ember-csi-operator/pull/22
