### ISSUE TITLE
Missing mountpoints

### ISSUE THREAD

**Issue by Akrog** [embercsi/ember-csi-operator#16]
There are a couple of mountpoints that are missing on the nodes:

- /var/lib/iscsi
- /run/udev

We need these among other things to share the iscsi nodes with the host, which will ensure we'll still see them after the container restarts.

**Comment by kirankt** [comment]
/run/udev already existed, but /var/lib/iscsi has been added in the PR: https://github.com/embercsi/ember-csi-operator/pull/22
