### ISSUE TITLE
Allow pinning the controller

### ISSUE THREAD

**Issue by Akrog** [embercsi/ember-csi-operator#18]
For the LVM backend we need to be able to pin the controller pod to a specific node.
The operator should support this.

**Comment by kirankt** [comment]
For this, I think, we have a default value to the operator that specifies a OCP/k8s node label e.g. infra and have the controller pods to land there. We can also have it configurable via the operator's config file...

e.g
controller-node-label: infra

Thoughts?

**Comment by Akrog** [comment]
I'm not sure that's good enough, as that would be driver dependent, not operator wide configuration.
For example you could deploy a Ceph driver that can land on any infra node, and then the LVM backend for non-production stuff, and for that one you need it to be pinned to a specific node within the infra nodes.

**Comment by kirankt** [comment]
As per our brief discussion, we can still do this with labels. If a single node needs to be tagged as 'lvm' the admin of the k8s/OCP cluster can just create a node label for it and we can use that label to pin the LVM pod.

**Comment by Akrog** [comment]
So we'll be adding label support to the operator, right?

**Comment by kirankt** [comment]
Yes. I'm currently working/testing it.

**Comment by Akrog** [comment]
Our deployments may have infrastructure and workload nodes, where the infra nodes are tainted with `NoSchedule`, so we normally wouldn't be able to create the controller node in there.

This means that we need to be able to add `tolerations` to the controller spec to be able to schedule the controller pod in those nodes.
