### ISSUE TITLE
Missing directory /var/lib/ember-csi/vols

### ISSUE THREAD

**Issue by cschwede** [embercsi/ember-csi-operator#38]
Commit cd81ebc10e0a392b5e5054cc1adce28a25a6f353 added support for the shared lock directory, however this requires an additional subdirectory or pods will fail to start:

  Warning  FailedMount             51s (x8 over 2m)  kubelet, node01          MountVolume.MountDevice failed for volume "pvc-67f73de2208311e9" : rpc error: code = Unknown desc = Exception calling application: [Errno 2] No such file or directory: u'/var/lib/ember-csi/vols/466e0060-a518-4f57-9f2a-cbe95c9629de'

After creating /var/lib/ember-csi/vols on the node01 it is working.

**Comment by Akrog** [comment]
This ember-csi PR should fix this issue: https://github.com/embercsi/ember-csi/pull/69

**Comment by cschwede** [comment]
Tested, fixed - thx!
