### ISSUE TITLE
Images are based on backend names

### ISSUE THREAD

**Issue by Akrog** [embercsi/ember-csi-operator#5]
Current code maps container images to be used using the backend name as the key:
```
    Image:   Conf.getDriverImage(ecsi.Spec.Backend),
```

It should be based on the driver to be used, as some drivers may need a custom container with specific packages.

**Comment by kirankt** [comment]
We discussed this briefly. Just to clarify, we're going to base this decision on the "volume_driver" value in X_CSI_BACKEND_CONFIG e.g cinder.volume.drivers.rbd.RBDDriver, which is a unique string and can be mapped to its corresponding image. Is this correct?

**Comment by Akrog** [comment]
Yes, that is correct, that way vendors can create their own containers with their particular external dependencies and we can either add the location to those containers in the operator repository or the admin can provide the configuration when deploying the operator.

**Comment by cschwede** [comment]
I think we can close this with commit 7efea7824dfcd55dfa53b3371a8e696d074306a7.
